name: "nix flake update"

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 23 * * 6' # runs weekly on Saturday at 23:00

jobs:
  nix-flake-update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        id: flake_update
        with:
          # Use the PAT here to trigger other workflows
          token: ${{ secrets.GH_PAT }}
          pr-title: "Update Nix flake inputs"
          pr-labels: |
            dependencies
            automated

      - name: Enable auto-merge
        if: steps.flake_update.outputs.pull-request-number != ''
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh pr merge --auto --squash "${{ steps.flake_update.outputs.pull-request-url }}"